// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FormmapController from "./formmap_controller"
application.register("formmap", FormmapController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ShowmapController from "./showmap_controller"
application.register("showmap", ShowmapController)

import TipsController from "./tips_controller"
application.register("tips", TipsController)
